credentials:
  usernames:
    admin:
      email: admin@example.com
      name: 관리자
      password: admin123
    teacher:
      email: teacher@example.com
      name: 교사
      password: teacher123
    student1:
      email: student1@example.com
      name: 김서윤
      password: student123
    student2:
      email: student2@example.com
      name: 김수민
      password: student123
    student3:
      email: student3@example.com
      name: 김승민
      password: student123
    student4:
      email: student4@example.com
      name: 문예진
      password: student123
    student5:
      email: student5@example.com
      name: 박준현
      password: student123
    student6:
      email: student6@example.com
      name: 오시원
      password: student123
    student7:
      email: student7@example.com
      name: 이공명
      password: student123
    student8:
      email: student8@example.com
      name: 이시원
      password: student123
    student9:
      email: student9@example.com
      name: 이지후
      password: student123
    student10:
      email: student10@example.com
      name: 장혜찬
      password: student123
    student11:
      email: student11@example.com
      name: 정나경
      password: student123
    student12:
      email: student12@example.com
      name: 조다민
      password: student123
    student13:
      email: student13@example.com
      name: 차지윤
      password: student123
    student14:
      email: student14@example.com
      name: 최성진
      password: student123
    student15:
      email: student15@example.com
      name: 추가영
      password: student123
    student16:
      email: student16@example.com
      name: 추연서
      password: student123
    student17:
      email: student17@example.com
      name: 허나경
      password: student123
    student18:
      email: student18@example.com
      name: 허지연
      password: student123
    student19:
      email: student19@example.com
      name: 김시온
      password: student123
    student20:
      email: student20@example.com
      name: 박수민
      password: student123      
cookie:
  expiry_days: 30
  key: yeonhap_test_key_123
  name: yeonhap_test_cookie

preauthorized:
  - teacher
  - student1
  - student2 
