credentials:
  usernames:
    teacher:
      email: teacher@example.com
      name: 교사
      password: teacher123
    student1:
      email: student1@example.com
      name: 학생1
      password: student123
    student2:
      email: student2@example.com
      name: 학생2
      password: student123

cookie:
  expiry_days: 30
  key: yeonhap_test_key_123
  name: yeonhap_test_cookie

preauthorized:
  - teacher
  - student1
  - student2 